version "4.10"

//Main
#include "ZScript/HDRiotShield.zsc" //fuck this, its bad

class PB_BallisticShield_Spawner : EventHandler
{
override void CheckReplacement(ReplaceEvent e) {
	if (!PB_HDWeps_AllowReplacement)
		return;
	switch (e.Replacee.GetClassName()) {
	
	//Ammo Pickups
	
		case 'PortableHealingItemBigger' 	: if (!random(0, 3)) {e.Replacement = "HDRiotShieldItem";}	break;
		}
	e.IsFinal = false;
	}
}